@echo off
echo Installing Capacitor dependencies...
call npm install @capacitor/core @capacitor/cli @capacitor/android
echo Initializing Capacitor...
npx cap init
echo Adding Android platform...
npx cap add android
echo Building Vite app...
npm run build
echo Copying web assets to Android...
npx cap copy android
echo Opening Android project in Android Studio...
npx cap open android
